[user]
name = "Zuruuh"
email = "zuruh.dev@proton.me"

[signing]
behavior = "own"
backend = "gpg"
key = "4C8921C0E8A4F68A78CE3EC6AFB2FC6B8FFFBCFB"

[git]
private-commits = '''description(glob:'private:*')'''

[ui]
diff-formatter = ":git"
pager = ["delta", "--pager", "less -FRX"]
merge-editor = 'mergiraf'

[ui.movement]
edit = true

[aliases]
push = ['git', 'push']
fetch = ['git', 'fetch']
move = ['bookmark', 'move', '--from=@--', '--to=@-', '--allow-backwards']
